### ISSUE TITLE
.ar6 compression file format from m602

### ISSUE THREAD

**Issue by mariolacko** [temisu/ancient#39]
Can you add support for ar6 format from [Manažér 602](https://cs.m.wikipedia.org/wiki/Manažer_M602) ?

**Comment by temisu** [comment]
Hi,

Basically I'm pretty open implementing new formats, as long they are
1. Identifyable in the bitstream
2. Not archive formats (like zip, lha) but compression formats (like gzip, bzip2)
3. Not terribly complicated, or broken.
4. It provides value to someone i.e. not so esoteric format that is not used at all.

In that tune I tried to find more information than what there is on that linked wikipedia page, but it looks like there really is not much. I can see there are two versions of the M602 and there is compression AR6 mentioned. But finding files or documentation is not possible.

Is there a chance you can help me trying to find more information about the format since most of the information seems to come from czech pages? Bare minimum would be to get some test files (and any documentation if it exists) Standalone compression tools would be great if they exist. Going through a huge DOS real mode executable like that M602 trying to find a compression algorithm is not really feasible, unless the format itself is copy of some known algorithm

Thanks

**Comment by mariolacko** [comment]
Hello. There in [files.zip](https://github.com/temisu/ancient/files/8017468/files.zip) are two files. files.txt and files.ar6 ar6 file, which is a compressed files.txt file.

**Comment by temisu** [comment]
Finally got some time to debug the file

`
00000000  41 52 36 00 46 49 4c 45  53 2e 41 52 36 20 20 20  |AR6.FILES.AR6   |
00000010  00 00 41 52 36 01 64 00  00 02 83 94 47 54 d9 71  |..AR6.d.....GT.q|
                ^^^^^^^^                 ^^^^^^^^^^^ ^^^^^
                File hdr.                timestamp   crc32
00000020  cd a2 f5 01 00 00 e8 05  00 00 09 00 00 00 46 49  |..............FI|
          ^^^^^ ^^^^^^^^^^^ ^^^^^^^^^^^^ ^^^^^^^^^^^ ^^^^^
          crc32 compr. len  uncompr. len name len    name
00000030  4c 45 53 2e 54 58 54 01  06 44 c4 1e 0c dd 94 c9  |LES.TXT..D......|
          ^^^^^^^^^^^^^^^^^^^^ ^^->
          name                 compressed stream
00000040  b6 b7 0c 4f d7 2c 08 5b  88 3c c5 51 bd a1 7b d3  |...O.,.[.<.Q..{.|
00000050  61 da 66 62 90 6d af af  63 7a de d6 1b d5 d6 76  |a.fb.m..cz.....v|
00000060  3d 71 b1 44 a8 52 4c 54  1c 8c 3f 0a 2d cd 66 28  |=q.D.RLT..?.-.f(|
00000070  ba 06 ce eb b4 d5 82 06  c2 42 ae 08 11 d9 05 ba  |.........B......|
00000080  12 10 16 0b 91 05 3c c1  47 84 2e 1b 4c 16 17 09  |......<.G...L...|
00000090  84 91 61 e0 e2 88 d7 6a  0f cf fb 72 40 02 76 1e  |..a....j...r@.v.|
000000a0  24 84 02 0e 58 3d 83 8b  81 b7 1e 78 38 38 5f 91  |$...X=.....x88_.|
000000b0  a0 e3 61 63 7f 34 71 ea  c3 35 2a 62 09 a6 bb cd  |..ac.4q..5*b....|
000000c0  b3 40 67 d5 5b 1c 5c e8  d0 b7 c1 5a 87 75 96 c0  |.@g.[.\....Z.u..|
000000d0  98 51 18 78 58 92 1e e5  20 83 81 9d 18 dd 38 0e  |.Q.xX... .....8.|
000000e0  3a 8c 68 a3 28 02 fe a2  9c c1 b4 a3 69 3c 42 eb  |:.h.(.......i<B.|
000000f0  30 3e 8a c4 15 22 09 be  ea 82 ee f6 24 36 3a 3a  |0>..."......$6::|
00000100  3a 6e b4 8e a0 be c0 65  fe 1f 28 7c a4 5a e2 e2  |:n.....e..(|.Z..|
00000110  c7 08 d7 a8 40 c4 2d 8d  63 c0 88 58 63 1d 05 23  |....@.-.c..Xc..#|
00000120  6d 1d 6b 81 c7 c6 0a 4b  47 60 84 46 47 0b 1d 4a  |m.k....KG`.FG..J|
00000130  19 c5 c4 c2 8c 36 5a 63  fb 03 a1 b0 c4 03 0b 1b  |.....6Zc........|
00000140  06 46 98 46 73 f2 16 97  04 37 62 eb c9 51 41 ed  |.F.Fs....7b..QA.|
00000150  68 25 7f 14 9e 51 14 3e  98 b9 46 cc 70 8d 42 11  |h%...Q.>..F.p.B.|
00000160  b0 53 5f 88 e2 51 58 31  a3 35 64 38 38 98 9b 8a  |.S_..QX1.5d88...|
00000170  e8 f5 e9 68 18 e3 91 18  e5 09 ca 28 8c 48 ae 89  |...h.......(.H..|
00000180  9e 1c 4d 44 18 3a f4 70  45 18 89 93 3b 7a 4c c2  |..MD.:.pE...;zL.|
00000190  94 19 30 a0 8a d3 5c 47  69 1d a3 8e 8a 23 84 2c  |..0...\Gi....#.,|
000001a0  0c be 20 9a 3f 36 0b b9  f4 83 bd dc a2 8f 82 9e  |.. .?6..........|
000001b0  e8 48 b2 e0 2c ac d8 51  6a fc e8 5d b1 56 99 b6  |.H..,..Qj..].V..|
000001c0  8e 03 3d aa a5 a4 a3 d9  9a 31 d0 6f bc 61 1a 0d  |..=......1.o.a..|
000001d0  63 c8 d2 d1 30 da 61 1d  05 3d ad 11 03 fa c2 88  |c...0.a..=......|
000001e0  81 1d 6d 94 8d cc 47 04  e3 1a 91 50 25 f4 75 88  |..m...G....P%.u.|
000001f0  98 3c 96 cb c7 61 bb c8  89 5c 4b 30 30 b1 23 d6  |.<...a...\K00.#.|
00000200  98 23 b9 38 69 96 69 13  aa 04 7d 23 c1 5c 31 18  |.#.8i.i...}#.\1.|
00000210  8b 8d 09 4e b1 d5 f4 31  79 20 59 4c d8 d0 d7 1a  |...N...1y YL....|
00000220  fa d3 d7 8f ab a3 d9 f6  3a 04 fc 03 41 52 36 02  |........:...AR6.|
                                          <-^^ ^^->
                             compressed stream dir. entry
00000230  64 00 00 02 83 94 47 54  d9 71 cd a2 f5 01 00 00  |d.....GT.q......|
00000240  e8 05 00 00 09 00 00 00  00 00 00 00 12 00 00 00  |................|
00000250  20 00 46 49 4c 45 53 2e  54 58 54 41 52 36 03 00  | .FILES.TXTAR6..|
00000260  00 00 00 2c 02 00 00 00  00 2f 00 00 00 00 00     |...,...../.....|
`

This is not just a compression format. this is archiver like zip (very close to zip in fact). This means that it does not really fit into the codebase. I'll keep the file as a reference in future if I extend the project to archivers (currently I'm working in opposite direction)

For the actual compression format - there does not seem to be any direct indication what it might be. And since I do not have access to the executable it is pretty hard to dig any further.

In any case thanks for following up on this but I currently do not see this being implemented
