### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by bkmgit** [temisu/ancient#41]
Do any implementations here have patents on them?

**Comment by temisu** [comment]
With software patents you can never be sure.

- LZW patents expired on 2004 world wide.
- Arithmetic coding patents (as used in these old implementations) have been expired as well. Although there are too many to count

Since these algorithms are all typically 30+ years old (some 40+ years) and patents are valid maximum 20 years the project should be safe. I've not implemented any algorithm that I know that has know issues.

But until someone and claims (a valid) patent on one of them, we can never be 100% sure
