### ISSUE TITLE
StuffitIt Support

### ISSUE THREAD

**Issue by dmt155** [temisu/ancient#5]
This is an amazing project!  I’d love to see StuffIt support for those 80s and 90s Mac archives. As far as I can tell, only The Unarchiver https://theunarchiver.com/ offers decompression support for these files.

**Comment by temisu** [comment]
Stuffit is really hard nut to solve.

First it contains some specifics of the old mac file system w. forks

Second it is really a collection of algorithms since it evolved a lot in its lifetime. (Also there is the X-version)

But yeah, it would be nice to add support for that - maybe someday. I'll leave this ticket open as a reminder

**Comment by sagamusix** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/StuffIt#Overview):

> The StuffIt and StuffIt X formats remain, unlike some other file compression formats, proprietary, and Smith Micro Software charge license fees for its use in other programs. Given this, few alternative programs support the format.

This might be a legal minefield and potentially endanger library users (and/or its developer).

**Comment by temisu** [comment]
I'm de-scoping all archival formats from the scope of this library and close this ticket - this would be another project if I ever get there
